# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.hostname = "go-sails-berkshelf"

  config.vm.network "forwarded_port", guest: 1337, host: 1337
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.omnibus.chef_version = :latest

  config.vm.box = "chef/centos-6.5"
  
  config.vm.network :private_network, ip: "192.168.253.38"
  
  config.vm.synced_folder "../app", "/home/vagrant/share"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    
    chef.run_list = [
        "recipe[go-sails::default]"
    ]
  end
end
